version: '3.7'
services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'fe'
      POSTGRES_PASSWORD: 'fe2022'
      POSTGRES_DB: 'heros'
    networks:
      - pgnet

  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'admin'
      MONGO_INITDB_ROOT_PASSWORD: 'senhaadmin'
      # MONGO_INITDB_DATABASE: 'herois'  //nao deve ter isso !
      MONGO_INITDB_USERNAME: 'felipe'
      MONGO_INITDB_PASSWORD: 'fe2022'

    volumes:
      - .docker/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    #  TODO: desconbrir pq isso nao funciona
    networks:
      - mongonet

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    networks:
      - pgnet

  mongoclient:
    container_name: mongoclient
    image: mongoclient/mongoclient
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      STARTUP_DELAY: 10
      # MONGO_URL: 'mongodb://felipe:fe2022@mongo:27017/admin'
    networks:
      - mongonet

networks:
  pgnet:
  mongonet:

  # api:
  #   image: node:latest
  #   container_name: api
  #   restart: always
  #   env_file:
  #     - .env
  #   ports:
  #     - '8080:8080'
  #   depends_on:
  #     - postgres
  #   networks:
  #     - pgnet
